global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: central-backend
    static_configs:
      - targets: ["central-backend:8000"]
    metrics_path: /metrics

  - job_name: perception-node
    static_configs:
      - targets:
          - "perception-node-zone:9091"
          - "perception-node-helmet:9092"
          - "perception-node-no-helmet:9093"
          - "perception-node-fire:9094"
        labels:
          job: perception-node
    metrics_path: /metrics
